"""add user models

Revision ID: 2832b61017aa
Revises: 1f9a27c70c8f
Create Date: 2026-01-12 10:22:49.396706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2832b61017aa'
down_revision = '1f9a27c70c8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('library', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['library'], ['libraries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('libraries', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('libraries', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    op.drop_table('users')
    # ### end Alembic commands ###
